# Generated by Django 4.2.6 on 2023-12-31 19:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HorarioInicio', models.TimeField(blank=True)),
                ('HorarioFin', models.TimeField(blank=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teefono')),
                ('ciudad', models.CharField(blank=True, max_length=20, verbose_name='Ciudad')),
                ('avatar', models.ImageField(default='avatar/default_avatar.png', upload_to='avatar/persona/%Y/%m/%d/', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TipoUsuario',
                'verbose_name_plural': 'TipoUsuarios',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.persona')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Usuario')),
                ('password', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.persona')),
                ('id_tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.tipousuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50, verbose_name='Motivo')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('fecha_reservada', models.DateField(null=True)),
                ('horario', models.CharField(max_length=50)),
                ('codigo_qr', models.CharField(max_length=255, unique=True, verbose_name='Codigo Qr')),
                ('estado_solicitud', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('procesado', 'Procesado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('estado', models.BooleanField(default=True)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.funcionario')),
                ('id_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.visitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='ResgistroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de ingreso')),
                ('estado', models.BooleanField(default=True)),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'ResgistroVisita',
                'verbose_name_plural': 'ResgistroVisitas',
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='horario',
            field=models.ManyToManyField(to='solicitudes.horario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.cargo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.persona'),
        ),
    ]
